//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TcpDataModel
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Badge
    {
        public int ID { get; set; }
        public long number { get; set; }
        public bool isEnabled { get; set; }
        public bool isMaster { get; set; }
        public bool forbidden { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
