//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TcpDataModel
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Badge
    {
        public Badge()
        {
            this.Opening = new ObservableCollection<Opening>();
        }
    
        public int ID { get; set; }
        public long number { get; set; }
        public bool isEnabled { get; set; }
        public bool isMaster { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual ObservableCollection<Opening> Opening { get; set; }
    }
}
