//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TcpDataModel
{
    using System;
    
    public enum BallLevel : int
    {
        Blanche = 0,
        Jaune = 1,
        Orange = 2,
        Verte = 3,
        Rouge = 4,
        Raquette = 5
    }
}
