//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TcpDataModel
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Booking
    {
        public int ID { get; set; }
        public string name { get; set; }
        public bool isSpecial { get; set; }
        public System.DateTime start { get; set; }
        public System.DateTime end { get; set; }
        public System.DateTime creationDate { get; set; }
        public bool Filmed { get; set; }
    
        public virtual BookingAggregation BookingAggregation { get; set; }
        public virtual Court Court { get; set; }
        public virtual Player Player1 { get; set; }
        public virtual Player Player2 { get; set; }
    }
}
