//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TcpDataModel
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Category
    {
        public Category()
        {
            this.Player = new ObservableCollection<Player>();
        }
    
        public int Id { get; set; }
        public string categoryName { get; set; }
    
        public virtual ObservableCollection<Player> Player { get; set; }
    }
}
