//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TcpDataModel
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Court
    {
        public Court()
        {
            this.Booking = new ObservableCollection<Booking>();
            this.Opening = new ObservableCollection<Opening>();
        }
    
        public int ID { get; set; }
        public string number { get; set; }
        public bool isCovered { get; set; }
    
        public virtual ObservableCollection<Booking> Booking { get; set; }
        public virtual ObservableCollection<Opening> Opening { get; set; }
    }
}
