//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TcpDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Court
    {
        public Court()
        {
            this.Booking = new HashSet<Booking>();
            this.Opening = new HashSet<Opening>();
        }
    
        public int ID { get; set; }
        public int number { get; set; }
        public bool isCovered { get; set; }
    
        public virtual ObservableCollection<Booking> Booking { get; set; }
        public virtual ObservableCollection<Opening> Opening { get; set; }
    }
}
