//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TcpDataModel
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Court
    {
        public Court()
        {
            this.Booking = new ObservableCollection<Booking>();
        }
    
        public int ID { get; set; }
        public string number { get; set; }
        public bool isCovered { get; set; }
    
        public virtual ObservableCollection<Booking> Booking { get; set; }
    }
}
