//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TcpDataModel
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Day
    {
        public Day()
        {
            this.PreferencePeriod = new ObservableCollection<PreferencePeriod>();
            this.TrainingPreferences = new ObservableCollection<TrainingPreferences>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
    
        public virtual ObservableCollection<PreferencePeriod> PreferencePeriod { get; set; }
        public virtual ObservableCollection<TrainingPreferences> TrainingPreferences { get; set; }
    }
}
