//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TcpDataModel
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class LogEntry
    {
        public int ID { get; set; }
        public System.DateTime timestamp { get; set; }
        public string reader_name { get; set; }
        public int tag_number { get; set; }
        public int reader_response { get; set; }
    }
}
