//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TcpDataModel
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class LogEntry
    {
        public int ID { get; set; }
        public System.DateTime timestamp { get; set; }
        public string reader_name { get; set; }
        public int tag_number { get; set; }
        public int reader_response { get; set; }
        public Nullable<int> Player_ID { get; set; }
    
        public virtual Player PlayerJeu { get; set; }
    }
}
