//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TcpDataModel
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class OpeningJeu
    {
        public int ID { get; set; }
        public System.DateTime time { get; set; }
        public Nullable<int> Court_ID { get; set; }
        public int Badge_ID { get; set; }
    
        public virtual Badge BadgeJeu { get; set; }
        public virtual Court CourtJeu { get; set; }
    }
}
