//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TcpDataModel
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class PaymentMethod
    {
        public PaymentMethod()
        {
            this.Payment = new ObservableCollection<Payment>();
        }
    
        public int Id { get; set; }
        public string methodName { get; set; }
    
        public virtual ObservableCollection<Payment> Payment { get; set; }
    }
}
