//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TcpDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public Player()
        {
            this.Badge = new HashSet<Badge>();
            this.PreferencePeriod = new HashSet<PreferencePeriod>();
            this.Booking = new HashSet<Booking>();
            this.Payment = new HashSet<Payment>();
            this.Category = new HashSet<Category>();
            this.TrainingPreferences = new HashSet<TrainingPreferences>();
        }
    
        public int ID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public System.DateTime birthDate { get; set; }
        public BallLevel level { get; set; }
        public string ranking { get; set; }
        public string email { get; set; }
        public string street { get; set; }
        public string zipCode { get; set; }
        public string city { get; set; }
        public string phone1 { get; set; }
        public string phone2 { get; set; }
        public PlayerStatus status { get; set; }
        public bool isEnabled { get; set; }
        public string passwordHash { get; set; }
        public System.DateTime lastLogin { get; set; }
        public string licenceNumber { get; set; }
    
        public virtual ObservableCollection<Badge> Badge { get; set; }
        public virtual ObservableCollection<PreferencePeriod> PreferencePeriod { get; set; }
        public virtual ObservableCollection<Booking> Booking { get; set; }
        public virtual ObservableCollection<Payment> Payment { get; set; }
        public virtual ObservableCollection<Category> Category { get; set; }
        public virtual ObservableCollection<TrainingPreferences> TrainingPreferences { get; set; }
    }
}
