//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TcpDataModel
{
    using System;
    
    public enum PlayerCategory : int
    {
        Hobby = 0,
        Competition = 1,
        Disabled = 2,
        TennisSchool = 3,
        Training = 4
    }
}
