//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TcpDataModel
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class PreferencePeriod
    {
        public int ID { get; set; }
        public int beginningHour { get; set; }
        public int endHour { get; set; }
        public int beginningMin { get; set; }
        public int endmin { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Day Day { get; set; }
    }
}
