//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TcpDataModel
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class ProductQuantitySet
    {
        public int Id { get; set; }
        public string Quantity { get; set; }
        public int Payment_ID { get; set; }
        public int Product_Id { get; set; }
    
        public virtual Payment PaymentJeu { get; set; }
        public virtual ProductSet ProductSet { get; set; }
    }
}
