//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TcpDataModel
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class TrainingPreferences
    {
        public int Id { get; set; }
        public Days day { get; set; }
        public int beginning { get; set; }
        public int end { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
